### ISSUE TITLE
[GO] [More fresh data] Display simple aggregate statistics on the front page and the "see data" page

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#17]
Let's start adding some descriptive statistics

<img width="469" alt="screen shot 2016-07-05 at 4 15 12 pm" src="https://cloud.githubusercontent.com/assets/10926168/16578192/c1552b90-42cb-11e6-84a6-9591b2ad5082.png">

Suggested entries and wording:
[SeeData-2.pdf](https://github.com/jliphard/CancerBase/files/347294/SeeData-2.pdf)

**Comment by ebcopur** [comment]
this is now live and updates every hour.

**Comment by jliphard** [comment]
WOW!
