### ISSUE TITLE
[GO] [Map] Option to not additionally randomize location

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#18]
We should have an option for people to be added at whatever location they gave - e.g. if they say Detroit, there should be a dot in Detroit. Some people do not want us to further randomize their location.  

Suggested wording:

"We usually strongly obscure the location you entered to protect your privacy. But some of us would like their dot on the map to appear right at the place they entered above. What would you like?"
 
Radio-(Strongly obscure location; more private) 
Radio-(Put your dot at location you entered; less private)

We should default this to the second option so that people will default to the most secure/private settings.

**Comment by ebcopur** [comment]
Added, will be published.
