### ISSUE TITLE
[GO] [Map] - How to display many people in one place?

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#21]
Assume many many people enter Detroit as their location. What then? A large dot whose radius scales with number of people? Change the color? Give each dot a random offset to scatter them around the specified location?

**Comment by jliphard** [comment]
Suggested fix - for every person, add a +/- 1.5 nm jitter to the analyzed location. This is about +/- 1/20th of a degree, assuming you are working in decimal degrees, i.e.:
finalLat = anonymizedLat + ((Math.random() - 0.5 ) / 10.0 );
finalLon = anonymizedLon + ((Math.random() - 0.5 ) / 10.0 );

**Comment by ebcopur** [comment]
Fixed, will be published.
