### ISSUE TITLE
[GO] [Visual Cleanup] Contributor tile formatting cleanup

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#26]
Tiles are inconsistently formatted - can we have the connection options aligned to the bottom via div style="position:absolute; bottom:0px;"? Example .CSS:

```javascript
<div class="person">
	<h4>AnneMarie Ciccarella</h4>
	<p>NYC<br>Patient, Research & Policy Advocate</p>
	<div style="position:absolute; bottom:0px;">
	<a href="http://chemobrainfog.com">chemobrainfog.com</a><br>
	<a href="https://twitter.com/chemobrainfog" class="twitter-follow-button" data-show-count="false">Follow @chemobrainfog</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
	if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
	</script>
	</div>
</div>
```

Current:
<img width="441" alt="screen shot 2016-07-04 at 1 58 45 pm" src="https://cloud.githubusercontent.com/assets/10926168/16551950/a83b1bba-41ef-11e6-8db8-7ba4af16a3ea.png">

Desired:
<img width="373" alt="screen shot 2016-07-04 at 2 01 23 pm" src="https://cloud.githubusercontent.com/assets/10926168/16551973/e27f8450-41ef-11e6-836e-7fd8c0f6ab9c.png">

**Comment by ebcopur** [comment]
Absolute positioning doesn't work with the current CSS framework in the app. Will look into another solution.

**Comment by jliphard** [comment]
I cleaned up the logos a bit on gitlab, and this can wait.
