### ISSUE TITLE
[Major Bug] Duplicate entries in Timeline when clicking save and when giving multiple initial DXs

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#30]
If you change or edit information in the initial questionnaire, then fields keep accumulating in your timeline. Every time you click save in the initial survey, new bubbles are added in the timeline. I think this is because you are appending entries to the corresponding database field instead of overwriting what was there before:
<img width="257" alt="screen shot 2016-07-05 at 11 22 09 am" src="https://cloud.githubusercontent.com/assets/10926168/16573129/ee0abed0-42a2-11e6-8a63-9b01437fd08f.png">
Desired behavior - clicking save multiple times should not keep adding initial DXs etc. 
Also, whatever is entered in the initial DX field should give precisely one bubble in the timeline - so if someone is DXed with metastatic breast cancer, that should be one entry, e.g. "Initial DX = metastatic breast cancer". Just take whatever a user enters in "initial DX" and use that to populate the initial DX bubble.

**Comment by ebcopur** [comment]
Fixed the duplicate bug.

But what if the user entered two cancer types in the initial DX? If I select "lung cancer" and "breast cancer" at the same time, what should the timeline box say?

**Comment by jliphard** [comment]
Both!

It's very very rare - but sometimes people have an initial diagnosis of cancer in two different organs. Probably 1% of people!

On Jul 5, 2016, at 2:41 PM, ebcopur <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed the duplicate bug.

But what if the user entered two cancer types in the initial DX? If I select "lung cancer" and "breast cancer" at the same time, what should the timeline box say?

-

**Comment by ebcopur** [comment]
So it should be still one box with both cancer names?

**Comment by jliphard** [comment]
Yes!!!!

To give an example, someone could have an initial DX of

Bone cancer and skin cancer

On Jul 5, 2016, at 2:46 PM, ebcopur <notifications@github.com<mailto:notifications@github.com>> wrote:


So it should be still one box with both cancer names?

-

**Comment by ebcopur** [comment]
Got it! Will do that when I get to the office.

**Comment by ebcopur** [comment]
This is now fixed.
