### ISSUE TITLE
Timeline is Gone??

### ISSUE THREAD

**Issue by AMCiccarella** [jliphard/CancerBase#31]
My timeline is gone and my diagnosis shows up three times. I signed up with FB only and used the same browser every time.

I had all of my surgeries listed along with medications, etc. It was a timeline of approximately 6 stages of treatment. It's all gone.
![screen shot 2016-07-05 at 11 15 05 am](https://cloud.githubusercontent.com/assets/20292453/16589601/d55580ec-42a1-11e6-9b46-3d657fb5b0da.png)
![screen shot 2016-07-05 at 11 15 22 am](https://cloud.githubusercontent.com/assets/20292453/16589612/dee84540-42a1-11e6-87c6-9da19e04c4c9.png)

**Comment by jliphard** [comment]
We're looking into it! Jan

On Jul 5, 2016, at 11:17 PM, AMCiccarella <notifications@github.com<mailto:notifications@github.com>> wrote:


My timeline is gone and my diagnosis shows up three times. I signed up with FB only and used the same browser every time.

I had all of my surgeries listed along with medications, etc. It was a timeline of approximately 6 stages of treatment. It's all gone.
[screen shot 2016-07-05 at 11 15 05 am]<https://cloud.githubusercontent.com/assets/20292453/16589601/d55580ec-42a1-11e6-9b46-3d657fb5b0da.png>
[screen shot 2016-07-05 at 11 15 22 am]<https://cloud.githubusercontent.com/assets/20292453/16589612/dee84540-42a1-11e6-87c6-9da19e04c4c9.png>

-

**Comment by ebcopur** [comment]
The duplicates issue is related to #30 where when updating the answers, duplicate would be created. This has been resolved today but I'm afraid the duplicates have stayed in the system, I deleted the extras manually.
Also while updating the answers, it seems the whole timeline was wiped out while re-creating it. This is now also resolved, and only the initial diagnosis tile will be updated. Really sorry for inconvenience!

**Comment by AMCiccarella** [comment]
All fixed on my side. Added back my timeline. Appears this is all fixed and ticket can be closed

**Comment by jliphard** [comment]
Yay - Big sigh of relief! Jan

On Jul 6, 2016, at 5:09 AM, AMCiccarella <notifications@github.com<mailto:notifications@github.com>> wrote:


All fixed on my side. Added back my timeline. Appears this is all fixed and ticket can be closed

-
