### ISSUE TITLE
Time Sensitive-Conference begins July 8

### ISSUE THREAD

**Issue by AMCiccarella** [jliphard/CancerBase#33]
Ovarian cancer conference begins on Friday.

http://www.ovariancancer.org/2016/01/04/2016-national-conference-registration-open/

Two action items:

1-Can we add ovarian to the list of cancer toggle buttons?

2-Is it possible to set up a "text to join" which returns a link to mobile friendly site to have people at the conference join cancerbase from their phones?

**Comment by regrounding** [comment]
> 1-Can we add ovarian to the list of cancer toggle buttons?

Dots should be TEAL

**Comment by ebcopur** [comment]
Ovarian has been added to the map in teal colour.
