### ISSUE TITLE
"About Us" Not Easily Found

### ISSUE THREAD

**Issue by AMCiccarella** [jliphard/CancerBase#36]
A fairly prominent ovarian cancer advocate wasn't happy with "transparency" ...
I know her well (Christina Lizaso)

Her Suggestion: Include the About Us link in the footer so it's easy to find.

That's the second issue with menu items today. Other was inability to add data easily. Let's take a look. Ease of use and finding info should be primary concern as we are getting this off the ground.

**Comment by jliphard** [comment]
Same as issue #37 - i've combined them
