### ISSUE TITLE
[GO] Direct link to "About Us" page

### ISSUE THREAD

**Issue by AMCiccarella** [jliphard/CancerBase#37]
Related to below (also, if logged in or already a member, this may not be an issue.... but we need to reach non members with this)

This seems to be an issue. I tried to send the link directly to the "about" page and I then tried to to it with Firefox. I got bounced around a few times before I could find the page. This one is important to people so it should be easy to access across all browsers. Speaking personally, this is the FIRST place I go when a new site it launched.

Going directly to /about redirects as indicated and the only way to access the page directly is via the menu which some people aren't seeing because they are accustomed to menu bars. We should think about a static menu bar. I know streamlined is the look but engaging people without issue is the goal.

Her comment:

you can tell them that http://www.cancerbase.org/about  redirects to http://www.cancerbase.org/login  which redirects to http://www.cancerbase.org/home  - so I can't direct ppl to the About Us page

**Comment by jliphard** [comment]
Yes - completely agree - people should be able to see the entire site without logging in, and we should avoid redirects. 

1/ http://www.cancerbase.org/about should just go to "About Us"

**Comment by ebcopur** [comment]
Fixed, will be published.
