### ISSUE TITLE
[GO] Some dots not appearing

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#39]
Greetings from Hong Kong. I helped a friend enter information for her mother, who just died. But, 12 hours later still no dot in Hong Kong? As a location, I think she just entered, "Hong Kong". Should she have entered "Hong Kong, China"? How reliable is our Lat/Lon finding for partial entries, and/or places with multiple map quest API results?

**Comment by ebcopur** [comment]
The entry in Hong Kong seems to be for Colorectal Cancer and that is not on the map yet.

**Comment by jliphard** [comment]
I'm beginning to think we should dispense with the 100 entry requirement and just plot dots (and new cancer types) when they are entered. She was super disappointed that her dead mom did not appear on the map...

**Comment by ebcopur** [comment]
Then we need to come up with colours for all organ types. So far this is the distribution:
<img width="277" alt="screen shot 2016-07-07 at 11 28 21" src="https://cloud.githubusercontent.com/assets/8260576/16648784/f8ae92dc-4435-11e6-8ed2-9a97fb5b0cb3.png">

**Comment by jliphard** [comment]
We have all those colors - I'll send them to you in a few hours. Jan

On Jul 7, 2016, at 5:29 PM, ebcopur <notifications@github.com<mailto:notifications@github.com>> wrote:


Then we need to come up with colours for all organ types. So far this is the distribution:
[screen shot 2016-07-07 at 11 28 21]<https://cloud.githubusercontent.com/assets/8260576/16648784/f8ae92dc-4435-11e6-8ed2-9a97fb5b0cb3.png>

-

**Comment by ebcopur** [comment]
Added all types of cancers submitted so far to the map.
