### ISSUE TITLE
[Go] Password recovery and "User exists" even if new registration

### ISSUE THREAD

**Issue by ebcopur** [jliphard/CancerBase#42]

**Comment by jliphard** [comment]
Heard from a few users that they are still struggling with registration. They get a "user exits" error even if they just signed up.

**Comment by ebcopur** [comment]
Yes there seems to be a problem with email signup atm, will push a fix.

**Comment by ebcopur** [comment]
the problem is fixed, password recovery will come later.

**Comment by jliphard** [comment]
Ok - I tested it and it looks much better now.
