### ISSUE TITLE
[Go] Accommodate start & stop dates for treatments

### ISSUE THREAD

**Issue by regrounding** [jliphard/CancerBase#45]
Other than surgery, most treatments occur over time. Can we add a STOP date in addition to a start date? This is esp true of mets therapies, where treatments often run as long as there is no progressing. There is value in being able to demonstrate how long a given therapy works in a patient subset. Phamas only given very general averages, and don't generally offer data about why some patients do better than others.

**Comment by jliphard** [comment]
This is a great point - let's add that in the next major release.

**Comment by ebcopur** [comment]
This is now live

**Comment by regrounding** [comment]
Fabulous!!!

**Comment by AMCiccarella** [comment]
Excellent!!!
