### ISSUE TITLE
Optimize automatic routing and use cases - where does user go post initial and repeated login?

### ISSUE THREAD

**Issue by regrounding** [jliphard/CancerBase#46]
In earlier renditions of the site there was a visible menu bar that ran across the top of each page. Can we bring that back for people who don't know to click on the menu icon?

**Comment by jliphard** [comment]
Most sites these days no longer have a visible menu bar. since we put the words "menu" next to the hamburger icon, it should be clear for virtually people that that is where they should click.

**Comment by regrounding** [comment]
We continue to get private and public feedback from users being confused about what do they do "next" or not finding the "give data" button. Can we solve this with a "Enter my data" or "Give data" or "Join" button?

**Comment by jliphard** [comment]
1/ We are changing the routing to automatically take them to the "give data" page after they join, so this problem should be resolved soon. 
2/ But I agree this is still not ideal - since when existing users login, they may not want to go to the give data page....

**Comment by jliphard** [comment]
Top menu bar (which is coming back) might help.

**Comment by regrounding** [comment]
Agreed!
