### ISSUE TITLE
Combining Cancer Types

### ISSUE THREAD

**Issue by regrounding** [jliphard/CancerBase#47]
Lymphoma was added to the map today (THANK YOU FOR ALL THE ADDITIONS!!!) 

My dad, who lives in the Phoenix area, joined on 30 June and has a diagnosis of mycosis fungoides - a kind of lymphoma. Is there a mechanism to flag mycosis fungoides as a kind of lymphoma and combine it with the rest of lymphoma? 

I can see multiple situations where someone enters a very specific focus - lobular carcinoma, a kind of breast cancer, for example - and that we'd want them to be placed on the map based on their biggest distinction (breast cancer) but available in the database in the narrowest way.

**Comment by jliphard** [comment]
This is what we do right now for map plotting - all the DXs get mapped onto about 15 organs - brain, breast, etc.
