### ISSUE TITLE
Add Menu Links horizontally across top of each page

### ISSUE THREAD

**Issue by Jack-Whelan** [jliphard/CancerBase#51]
Suggest we display each of the Menu links horizontally across the top of each page.  And as we add more sub-links with a simple tree structure, users can simply click  Home, Give Data, SeeData, Settings, About Us, LogOut, Help!

Me thinks many users don't presently understand the option to click Menu.

Jack

**Comment by jliphard** [comment]
Yes - fixed - will be rolled out with next release after some more testing.
