### ISSUE TITLE
Feature request - new question - please tell us about your cancer - please add to box one, after question 5. 

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#6]
New text field and question - 

**Standard surveys tend to leave many people out - because we are all different. If you like, you can tell us in your own words about your cancer.** 

we are getting some facebook posts with people giving much more information - but right now people cannot add that info to cancerbase - key is that this is a **multiline text box** so people can write a little paragraph - suggest limiting it to 1000 characters???

**Comment by ebcopur** [comment]
Done, will be published.

**Comment by KnowledgeGarden** [comment]
Sounds like  room for some NLP?
Also, sounds like room for something akin to a triage tree as a means to gain even more information on a pt (member).

**Comment by jliphard** [comment]
Hi Jack - yes - the most immediate problem we are facing is that our dropdown list of initial cancer diagnoses is not covering all the possibilities, and we do not want to end up with a dropdown list with 2000+ entires. What do you think is the best solution?
