### ISSUE TITLE
[RESOLVED IN GITLAB] Wording improvement - "Sign up" -> "Sign in"

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#8]

**Comment by ebcopur** [comment]
Why was this necessary? Don't sign in and login mean the same thing? Wasn't "Sign up/ login" there because user can register OR login with the same button?

**Comment by jliphard** [comment]
Yes - you are totally right. How about "Join / Login"? Jan

On Jul 1, 2016, at 3:54 AM, ebcopur <notifications@github.com<mailto:notifications@github.com>> wrote:


Why was this necessary? Don't sign in and login mean the same thing? Wasn't "Sign up/ login" there because user can register OR login with the same button?

-
