### ISSUE TITLE
Registration option broken and flow improvement

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#9]
.....when I hit the 'Register' button...nothing happened, so it appeared I hadn't registered. 
Suggest: 1. giving an acknowledgement that Registration was completed (when logged in via that option) and then bring up automatically the follow-on pages.

**Comment by KnowledgeGarden** [comment]
Experience the same just now. No clue whether I am registered. Tried signing up; no cigar.

**Comment by jliphard** [comment]
Are you familiar with Angular2 and node.js? If so - can you help us code? We really need help right now...

**Comment by KnowledgeGarden** [comment]
Thanks for asking. In my own repo here, I have one Angular prototype which was abandoned. Don't get me wrong: Angular is awesome; for me and my particular limitations, it was to constraining, so I returned to Node/Express and migrated all the really complex database work out of Node to a Java servlet platform to drive my topic map. OTOH, our interests are so closely aligned that I wonder where we have opportunities to collaborate. You can view a far-from-complete instance of my work at http://www.topicquests.org:3000/ -- that's a topic map-driven web system.

**Comment by ebcopur** [comment]
After registration the user will now be taken to the login page with an appropriate message of confirmation. I wasn't able to fail the registration process in any way though. And it seems there are many people who registered and submitted info via here. 

While logging in, it is username and password, rather than email and password, maybe the problem lies there?

**Comment by ebcopur** [comment]
The fix is not published yet, by the way.

**Comment by jliphard** [comment]
> While logging in, it is username and password, rather than email and password, maybe the problem lies there?
> 

Yes, it might be a wording issue - but I can’t think of a better way to phrase things - let’s stick with what you have… As long as the login field clear says “Username:” that should be ok.

Jan

**Comment by jliphard** [comment]
I just saw what other sites do - they allow the users to use either the username or the email in the "user" field for the login - that would reduce problems

**Comment by ebcopur** [comment]
Yes nice - will do that.

**Comment by KnowledgeGarden** [comment]
Indeed! A confession: I made a false assumption and went with email; I got in with username just now, meaning it's more my bad than anything else. I agree with the suggested change.
